### ISSUE TITLE
Any reason for using ALL CAPS as variable names.

### ISSUE THREAD

**Issue by karthikphm** [iam-aniruddha/Assignment_2#1]
https://github.com/iam-aniruddha/Assignment_2/blob/649eee7083e8d32ec9db7cff9d599b7c4d86f6d6/Ques_3.py#L18

**Comment by iam-aniruddha** [comment]
In Python, a variable written in uppercase is typically considered as a constant, meaning its value should not be altered throughout the program. Therefore, to avoid modifying the filename globally, it is a common practice to use an uppercase variable name, that's why I have used the variable name in All Caps letters.
